const {services,professionals,validate}=PetVida;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},uid=()=>crypto.randomUUID();
const key='petvida-demo-v1',labels={pendente:'Pendente',confirmado:'Confirmado',concluido:'Concluído',cancelado:'Cancelado',falta:'Falta'};
function seed(){return {tutors:[{id:'u1',name:'Mariana Oliveira',contact:'Contato de exemplo'},{id:'u2',name:'Lucas Pereira',contact:'Contato de exemplo'},{id:'u3',name:'Ana Costa',contact:'Contato de exemplo'}],pets:[{id:'p1',name:'Bento',species:'Cão',breed:'Golden retriever',tutor:'u1',birth:''},{id:'p2',name:'Luna',species:'Gato',breed:'Sem raça definida',tutor:'u2',birth:''},{id:'p3',name:'Mel',species:'Cão',breed:'Shih-tzu',tutor:'u3',birth:''}],appointments:[{id:'a1',pet:'p1',service:'Consulta',professional:'g',date:today(),time:'09:00',status:'confirmado',notes:'Atendimento de rotina. Registro fictício.',returnDate:''},{id:'a2',pet:'p3',service:'Banho e tosa',professional:'t1',date:today(),time:'10:00',status:'pendente',notes:'',returnDate:''},{id:'a3',pet:'p2',service:'Vacinação',professional:'c',date:today(),time:'11:30',status:'pendente',notes:'',returnDate:''},{id:'a4',pet:'p1',service:'Banho',professional:'t2',date:today(),time:'14:00',status:'confirmado',notes:'',returnDate:''}]};}
let state;try{state=JSON.parse(localStorage.getItem(key));if(!state||!['tutors','pets','appointments'].every(k=>Array.isArray(state[k])))state=seed()}catch{state=seed()}
let view='inicio',filterDate=today(),petSearch='',agendaService='',agendaProfessional='',historyPet='';
function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{toast('Não foi possível salvar neste navegador. Os dados permanecerão apenas nesta sessão.')}}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500)}
const pet=id=>state.pets.find(p=>p.id===id),tutor=id=>state.tutors.find(t=>t.id===id),pro=id=>professionals.find(p=>p.id===id),dateText=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR'),options=(items,value)=>items.map(([id,label])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(label)}</option>`).join('');
const petOptions=v=>options(state.pets.map(p=>[p.id,`${p.name} · ${tutor(p.tutor)?.name}`]),v);
function rows(list){if(!list.length)return '<div class="empty">Nenhum atendimento encontrado para estes filtros.</div>';return `<div class="table-wrap"><table><thead><tr><th>Horário</th><th>Pet e tutor</th><th>Serviço</th><th>Profissional</th><th>Status</th><th>Ações</th></tr></thead><tbody>${list.map(a=>`<tr><td><b>${esc(a.time)}</b><small>${dateText(a.date)}</small></td><td class="pet-name">${esc(pet(a.pet)?.name)}<small>${esc(tutor(pet(a.pet)?.tutor)?.name)}</small></td><td>${esc(a.service)}<small>${services[a.service].duration} minutos</small></td><td>${esc(pro(a.professional)?.name)}</td><td><span class="badge ${a.status}">${labels[a.status]}</span></td><td><div class="row-actions"><button data-edit="${a.id}">Detalhes</button>${a.status==='pendente'?`<button data-confirm="${a.id}">Confirmar</button>`:''}${['pendente','confirmado'].includes(a.status)?`<button data-complete="${a.id}">Concluir</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`}
function render(){const titles={inicio:'Visão geral',agenda:'Agenda',pets:'Tutores e pets',historico:'Histórico de cuidados',lembretes:'Lembretes'};$('#title').textContent=titles[view];document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false')});const day=state.appointments.filter(a=>a.date===today());let html='';
if(view==='inicio'){html=`<div class="welcome"><div><h2>Um novo dia de cuidado.</h2><p>Acompanhe a agenda e mantenha cada atendimento em dia.</p></div><span class="date-chip">${new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</span></div><div class="stats">${[['Atendimentos hoje',day.filter(a=>a.status!=='cancelado').length,'Consultas e estética'],['A confirmar',day.filter(a=>a.status==='pendente').length,'Acompanhe os tutores'],['Concluídos',day.filter(a=>a.status==='concluido').length,'Cuidados registrados'],['Cancelamentos',day.filter(a=>a.status==='cancelado').length,'Horários liberados']].map(([label,n,note])=>`<div class="stat"><span>${label}</span><strong>${n}</strong><small>${note}</small></div>`).join('')}</div><div class="panel"><div class="panel-heading"><div><h2>Agenda de hoje</h2><p>Todos os cuidados, em um só lugar.</p></div><button data-view="agenda">Ver agenda →</button></div>${rows(day.sort((a,b)=>a.time.localeCompare(b.time)))}</div>`}
if(view==='agenda'){const list=state.appointments.filter(a=>a.date===filterDate&&(!agendaService||a.service===agendaService)&&(!agendaProfessional||a.professional===agendaProfessional)).sort((a,b)=>a.time.localeCompare(b.time));html=`<div class="panel"><div class="filters"><label>Data<input id="filter-date" type="date" value="${filterDate}"></label><label>Serviço<select id="filter-service"><option value="">Todos os serviços</option>${options(Object.keys(services).map(s=>[s,s]),agendaService)}</select></label><label>Profissional<select id="filter-pro"><option value="">Todos os profissionais</option>${options(professionals.map(p=>[p.id,p.name]),agendaProfessional)}</select></label></div>${rows(list)}</div>`}
if(view==='pets'){const list=state.pets.filter(p=>(p.name+' '+tutor(p.tutor)?.name).toLocaleLowerCase().includes(petSearch.toLocaleLowerCase()));html=`<div class="panel-heading"><label>Buscar pet ou tutor<input id="search" type="search" placeholder="Nome do pet ou responsável" value="${esc(petSearch)}"></label><div class="row-actions"><button id="add-tutor">+ Cadastrar tutor</button><button class="primary" id="add-pet">+ Cadastrar pet</button></div></div><div class="grid">${list.map(p=>`<article class="pet-card"><span class="animal" aria-hidden="true">${p.species==='Gato'?'🐈':'🐾'}</span><h2>${esc(p.name)}</h2><p>${esc(p.species)} · ${esc(p.breed||'Raça não informada')}<br>Tutor: ${esc(tutor(p.tutor)?.name)}<br>${esc(tutor(p.tutor)?.contact)}</p><div class="row-actions"><button data-profile="${p.id}">Ver histórico</button><button data-pet-edit="${p.id}">Editar cadastro</button></div></article>`).join('')||'<div class="empty">Nenhum pet encontrado.</div>'}</div><div class="panel" style="margin-top:24px"><h2>Tutores cadastrados</h2>${state.tutors.map(t=>`<div class="reminder"><div><b>${esc(t.name)}</b><p>${esc(t.contact)}</p></div><button data-tutor-edit="${t.id}">Editar tutor</button></div>`).join('')}</div>`}
if(view==='historico'){if(!historyPet&&state.pets.length)historyPet=state.pets[0].id;const p=pet(historyPet),list=state.appointments.filter(a=>a.pet===historyPet).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));html=`<div class="panel"><label>Selecione um pet<select id="history-pet">${petOptions(historyPet)}</select></label>${p?`<div class="panel-heading" style="margin-top:24px"><div><h2>${esc(p.name)}</h2><p>${esc(p.species)} · ${esc(p.breed||'Raça não informada')} · Tutor: ${esc(tutor(p.tutor)?.name)}</p><p>Nascimento: ${p.birth?dateText(p.birth):'Não informado'}</p></div><button data-pet-edit="${p.id}">Editar pet</button></div>`:''}<div class="timeline">${list.map(a=>`<article><span class="badge ${a.status}">${labels[a.status]}</span><h3 style="margin-top:10px">${dateText(a.date)} · ${esc(a.service)}</h3><p>${esc(pro(a.professional)?.name)} · ${esc(a.time)}</p><p>${esc(a.notes||'Sem observações registradas.')}</p>${a.returnDate?`<p>Retorno registrado: ${dateText(a.returnDate)}</p>`:''}<button data-edit="${a.id}">Abrir atendimento</button></article>`).join('')||'<div class="empty">Ainda não há atendimentos registrados para este pet.</div>'}</div></div>`}
if(view==='lembretes'){const list=state.appointments.filter(a=>a.status==='pendente'||(a.returnDate&&a.status==='concluido'));html=`<div class="panel"><h2>Confirmações e retornos</h2><p>Confira a prévia antes de simular o lembrete. Nenhuma mensagem será enviada.</p>${list.map(a=>`<div class="reminder"><div><h3>${esc(pet(a.pet)?.name)} · ${a.status==='pendente'?'Confirmação de atendimento':'Retorno preventivo'}</h3><p>${esc(message(a))}</p></div><button data-remind="${a.id}">Simular lembrete</button></div>`).join('')||'<div class="empty">Nenhum lembrete pendente.</div>'}</div>`}
$('#content').innerHTML=html;
}
function message(a){return a.status==='pendente'?`Olá, ${tutor(pet(a.pet)?.tutor)?.name}! Podemos confirmar ${a.service.toLowerCase()} de ${pet(a.pet)?.name} na PetVida em ${dateText(a.date)}, às ${a.time}?`:`Olá, ${tutor(pet(a.pet)?.tutor)?.name}! Há um retorno registrado para ${pet(a.pet)?.name} em ${dateText(a.returnDate)}. Entre em contato para agendar.`}
let onSubmit;
function openForm(title,fields,handler){$('#dialog-title').textContent=title;$('#fields').innerHTML=fields;$('#error').textContent='';onSubmit=handler;$('#modal').showModal()}
const field=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
function appointmentForm(id){if(!state.pets.length){toast('Cadastre um tutor e um pet antes de agendar.');return}const a=state.appointments.find(a=>a.id===id)||{id:uid(),date:filterDate,time:'09:00',service:'Consulta',professional:'g',status:'pendente',pet:state.pets[0].id};openForm(id?'Detalhes do atendimento':'Novo agendamento',`<label>Pet<select name="pet" required>${petOptions(a.pet)}</select></label><label>Serviço<select name="service" id="service">${options(Object.keys(services).map(s=>[s,s]),a.service)}</select></label><label>Profissional<select name="professional" id="professional"></select></label><label>Duração<input id="duration" readonly></label>${field('Data','date',a.date,'date','required')}${field('Horário','time',a.time,'time','required step="300"')}<label>Status<select name="status">${options(Object.entries(labels),a.status)}</select></label>${field('Data de retorno opcional','returnDate',a.returnDate,'date')}<label class="wide">Observações do atendimento<textarea name="notes" rows="3" maxlength="3000">${esc(a.notes)}</textarea></label><p class="wide" style="font-size:13px;color:#64766e;margin:0">Durações e funcionamento das 08h às 18h são exemplos para o protótipo.</p>`,data=>{const next={...a,...data};if(!pet(next.pet))return 'Selecione um pet cadastrado.';const error=validate(next,state.appointments);if(error)return error;if(next.returnDate&&next.returnDate<next.date)return 'O retorno não pode ocorrer antes do atendimento.';if(next.status==='cancelado'&&a.status!=='cancelado'&&!confirm('Cancelar este atendimento e liberar o horário?'))return 'Cancelamento não realizado.';const index=state.appointments.findIndex(x=>x.id===a.id);if(index<0)state.appointments.push(next);else state.appointments[index]=next;return ''});const sync=()=>{const service=$('#service').value;$('#professional').innerHTML=options(professionals.filter(p=>p.role===services[service].role).map(p=>[p.id,p.name]),a.professional);$('#duration').value=services[service].duration+' minutos'};sync();$('#service').onchange=sync}
function tutorForm(id){const t=tutor(id)||{id:uid(),name:'',contact:''};openForm(id?'Editar tutor':'Cadastrar tutor',field('Nome do tutor','name',t.name,'text','required maxlength="100"')+field('Telefone ou e-mail','contact',t.contact,'text','required maxlength="120"'),data=>{if(!data.name.trim()||!data.contact.trim())return 'Preencha o nome e o contato.';const item={...t,name:data.name.trim(),contact:data.contact.trim()},i=state.tutors.findIndex(x=>x.id===t.id);if(i<0)state.tutors.push(item);else state.tutors[i]=item;return ''})}
function petForm(id){if(!state.tutors.length){toast('Cadastre primeiro o tutor responsável.');return}const p=pet(id)||{id:uid(),name:'',species:'Cão',breed:'',tutor:state.tutors[0].id,birth:''};openForm(id?'Editar pet':'Cadastrar pet',field('Nome do pet','name',p.name,'text','required maxlength="80"')+`<label>Espécie<select name="species">${options(['Cão','Gato','Outro'].map(s=>[s,s]),p.species)}</select></label>`+field('Raça opcional','breed',p.breed,'text','maxlength="80"')+field('Nascimento opcional','birth',p.birth,'date',`max="${today()}"`)+`<label class="wide">Tutor responsável<select name="tutor">${options(state.tutors.map(t=>[t.id,t.name]),p.tutor)}</select></label>`,data=>{if(!data.name.trim()||!tutor(data.tutor))return 'Informe o nome e um tutor válido.';const item={...p,...data,name:data.name.trim()},i=state.pets.findIndex(x=>x.id===p.id);if(i<0)state.pets.push(item);else state.pets[i]=item;return ''})}
$('#form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)),error=onSubmit(data);if(error){$('#error').textContent=error;return}save();$('#modal').close();render();toast('Registro salvo com sucesso.')};$('#close').onclick=$('#cancel').onclick=()=>$('#modal').close();$('#new').onclick=()=>appointmentForm();$('#reset').onclick=()=>{if(confirm('Restaurar os exemplos? Os cadastros e alterações deste navegador serão substituídos.')){state=seed();historyPet='';save();render();toast('Dados de demonstração restaurados.')}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render()}if(b.dataset.edit)appointmentForm(b.dataset.edit);if(b.dataset.petEdit)petForm(b.dataset.petEdit);if(b.dataset.tutorEdit)tutorForm(b.dataset.tutorEdit);if(b.dataset.profile){historyPet=b.dataset.profile;view='historico';render()}if(b.id==='add-tutor')tutorForm();if(b.id==='add-pet')petForm();if(b.dataset.confirm){const a=state.appointments.find(a=>a.id===b.dataset.confirm);a.status='confirmado';save();render();toast('Atendimento confirmado.')}if(b.dataset.complete){appointmentForm(b.dataset.complete);$('#form select[name="status"]').value='concluido'}if(b.dataset.remind)toast('Simulação concluída. Nenhuma mensagem foi enviada.');});
document.addEventListener('change',e=>{if(e.target.id==='filter-date'){filterDate=e.target.value;render()}if(e.target.id==='filter-service'){agendaService=e.target.value;render()}if(e.target.id==='filter-pro'){agendaProfessional=e.target.value;render()}if(e.target.id==='history-pet'){historyPet=e.target.value;render()}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;petSearch=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(pos,pos)}});render();
